openapi: 3.0.3
info:
  title: Gestão de Alunos
  version: 1.0.0
  contact:
    name: Fabiana
    email: fabypetrovick@gmail.com
    url: https://amais.fabiana.petrovick.work
  description: Documentação para Gestão de Alunos

servers:
  - url: "https://amais.fabiana.petrovick.work"
    description: Produção

paths:
  /students:
    post:
      tags:
        - Students
      $ref: "./students/register-students.yml"
    get:
      tags:
        - Students
      $ref: "./students/list-students.yml"
  /students/{ra}:
    get:
      tags:
        - Students
      $ref: "./students/list-student-by-ra.yml"
    put:
      tags:
        - Students
      $ref: "./students/update-student-by-ra.yml"
    delete:
      tags:
        - Students
      $ref: "./students/delete-student-by-ra.yml"