
networks:
  shared-services:
    external: true
    driver: bridge 

services:
  postgres-db:
    container_name: postgres-db
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: app
    networks:
      - shared-services
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U docker -d app"]
      interval: 5s
      timeout: 3s
      retries: 10
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      target: dev
    environment:
      - NODE_ENV=dev
      - DEBUG=${DEBUG}
      - WATCH_FILES=${WATCH_FILES}
      - DATABASE_URL=postgresql://docker:docker@postgres-db:5432/app?schema=public
    volumes:
      - ".:/application"
      # - "~/.aws/credentials:/root/.aws/credentials"
      # - "~/.aws/config:/root/.aws/config"
    networks:
      - shared-services
    ports:
      - "9229:9229"
      - "3333:3333"

volumes:
  db_data:
